id: 7ee0e9da-c27f-43f2-b548-132e4cf520bc
full_slug: public-cloud-storage-pca-capabilities-limitations
reference_category: public-cloud-storage-object-storage-openstack-swift-archive-storage-class-specifics