id: 5a9a9fc8-fa42-4f90-9739-935417bce558
<<<<<<< HEAD
full_slug: public-cloud-ai-endpoints-function-calling-langchain4j
=======
full_slug: public-cloud-ai-endpoints-function-calling-langchain4j
reference_category: public-cloud-ai-and-machine-learning-ai-endpointstutorials
>>>>>>> adbe315c009c5bc773f150eac239ee9da2786ea7
