id: 2bf42a11-73a4-4b07-a526-8cb170390dff
full_slug: public-cloud-kubernetes-migrating-nginx-to-traefik
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-configuration-traffic-management
