id: 44b0b6b8-1987-4542-9033-e103feb893e5
full_slug: public-cloud-kubernetes-migrate-iolb-to-public-cloud-loadbalancer
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-configuration-traffic-management