id: 3376a99e-2f52-4264-a4ee-d4f42cd5e5cd
full_slug: yokohama-upgrade
translation_banner: true
reference_category: account-and-service-management-account-information-servicenow-upgrade
banner: public-cloud-voucher
disable_languages:
- fr-ca
- en-asia