#!/usr/bin/env node
/**
 * One-time conversion script: reads base/links/ files and generates config/links.ts
 *
 * Usage:
 *   npx tsx scripts/convert-links.ts
 *
 * Reads the 269 link definition files from base/links/, maps the 16 legacy locale
 * codes to the 8 Rspress locales, and writes the centralized config/links.ts.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT_DIR = path.resolve(import.meta.dirname, '..');
const LINKS_DIR = path.join(ROOT_DIR, 'base', 'links');
const OUTPUT_FILE = path.join(ROOT_DIR, 'config', 'links.ts');

/**
 * Maps legacy locale codes (used in base/links/ files) to Rspress locale codes.
 * Only the primary locale per language is kept; regional variants (en-asia, etc.) are dropped.
 */
const LOCALE_MAP: Record<string, string> = {
  'fr-fr': 'fr',
  'en-gb': 'en',
  'de-de': 'de',
  'es-es': 'es',
  'it-it': 'it',
  'pl-pl': 'pl',
  'pt-pt': 'pt',
};

interface LinkEntry {
  [locale: string]: string;
}

function walkDir(dir: string, prefix: string = ''): Record<string, LinkEntry> {
  const map: Record<string, LinkEntry> = {};
  if (!fs.existsSync(dir)) return map;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const subMap = walkDir(
        fullPath,
        prefix ? `${prefix}/${entry.name}` : entry.name,
      );
      Object.assign(map, subMap);
    } else if (entry.isFile()) {
      const linkKey = prefix ? `${prefix}/${entry.name}` : entry.name;
      const content = fs.readFileSync(fullPath, 'utf-8');
      const localeMap: LinkEntry = {};

      // Parse each line: - [locale](url)
      const lineRegex = /^\s*-\s*\[([^\]]+)\]\(([^)]+)\)/gm;
      for (const match of content.matchAll(lineRegex)) {
        const legacyLocale = match[1];
        const url = match[2];
        const rspressLocale = LOCALE_MAP[legacyLocale];
        if (rspressLocale) {
          localeMap[rspressLocale] = url;
        }
      }

      if (Object.keys(localeMap).length > 0) {
        map[linkKey] = localeMap;
      }
    }
  }

  return map;
}

function generateTypeScript(links: Record<string, LinkEntry>): string {
  const lines: string[] = [];

  lines.push(
    '// Auto-generated by scripts/convert-links.ts — do not edit manually',
  );
  lines.push("import type { Locale } from './shared';");
  lines.push('');
  lines.push(
    'export type LinkMap = Record<string, Partial<Record<Locale, string>>>;',
  );
  lines.push('');
  lines.push('export const externalLinks: LinkMap = {');

  // Sort keys for stable output
  const sortedKeys = Object.keys(links).sort();
  const localeOrder = ['fr', 'en', 'de', 'es', 'it', 'pl', 'pt'];

  for (const key of sortedKeys) {
    const entry = links[key];
    const escapedKey = key.includes("'") ? `"${key}"` : `'${key}'`;
    lines.push(`  ${escapedKey}: {`);

    for (const locale of localeOrder) {
      if (entry[locale]) {
        // Escape single quotes in URLs
        const escapedUrl = entry[locale]
          .replace(/\\/g, '\\\\')
          .replace(/'/g, "\\'");
        lines.push(`    '${locale}': '${escapedUrl}',`);
      }
    }

    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

// Main
console.log('Converting base/links/ → config/links.ts...');
const links = walkDir(LINKS_DIR);
const keyCount = Object.keys(links).length;
console.log(`  Parsed ${keyCount} link definitions`);

const output = generateTypeScript(links);
fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`  Written to ${OUTPUT_FILE}`);
console.log('Done.');
