id: eb06c906-ff8a-4a5b-a10b-1b06ac2be771
full_slug: public-cloud-databases-database-operator
reference_category: public-cloud-containers-orchestration-managed-kubernetes-k8s-public-cloud-databases-database-operator
